### ISSUE TITLE
Кодревью 1

### ISSUE THREAD

**Issue by AlexeiYakimov** [AmrAbuelhamd/Recipes2#1]
https://github.com/AmrAbuelhamd/Recipes2/blob/07ec466ea1d331378845cb8a602134450b4e1939/app/build.gradle#L60
Будем использовать `org.jetbrains.kotlinx:kotlinx-serialization-json` -  это скорее указание на будущее. Здесь можно не править.

https://github.com/AmrAbuelhamd/Recipes2/blob/07ec466ea1d331378845cb8a602134450b4e1939/app/build.gradle#L88
хорошо, но лучше использовать стандартный https://developer.android.com/topic/libraries/view-binding , поскольку лишний сахар в таком важном деле, как инициализация биндинга, может навредить. Здесь можно не править.

https://github.com/AmrAbuelhamd/Recipes2/blob/master/app/src/main/java/com/blogspot/soyamr/recipes2/Utils.kt
лишний исходник, использующийся для разного рода опробываний. Из приложения следует удалить, а опробывания производить в scratch-файлах https://medium.com/@shivam.gosavi340_58315/productivity-hack-androidstudio-kotlin-scratch-file-e17cfde152c6

https://github.com/AmrAbuelhamd/Recipes2/blob/master/app/src/main/res/layout/recyclerview_item.xml
именование не отражает сути. Это элемент какого-то конкретного списка, поэтому в названии следует отразить его принадлежность к рецептам

https://github.com/AmrAbuelhamd/Recipes2/blob/07ec466ea1d331378845cb8a602134450b4e1939/app/src/main/java/com/blogspot/soyamr/recipes2/data/database/model/Recipe.kt#L21 
https://github.com/AmrAbuelhamd/Recipes2/blob/07ec466ea1d331378845cb8a602134450b4e1939/app/src/main/java/com/blogspot/soyamr/recipes2/data/network/model/Recipe.kt#L15
модель данных в дата-слое - это частное представление доменной модели. Она не должна знать, как конвертировать себя в доменное представление - такая конвертация вне ее зоны ответственности. Следует завести отдельный исходник в дата-слое, в котором хранить все конвертации: из домена в дату и обратно. Можно реализовать это с помощью функций-расширений.

https://github.com/AmrAbuelhamd/Recipes2/blob/07ec466ea1d331378845cb8a602134450b4e1939/app/src/main/java/com/blogspot/soyamr/recipes2/data/database/model/Converters.kt#L12
для каждой конвертации создается новый объект `Gson` - это непродуктивно. Поскольку в проекте используется DI, было бы очевидным иметь единый экземпляр Gson и инжектить его всюду. Поскольку едва ли получится заинжектить экземпляр в класс `Converters`, то нам следует откуда-то брать инстанс класса `Gson`. Видимо, придется его хранить в статическом объекте: брать оттуда для DI, а где DI не работает - брать напрямую. Простейший пример:
```
object GsonInstance {
  val gson = Gson()
}
```

https://github.com/AmrAbuelhamd/Recipes2/blob/07ec466ea1d331378845cb8a602134450b4e1939/app/src/main/java/com/blogspot/soyamr/recipes2/domain/di/UseCaseModule.kt#L16
здесь и ниже - названия функций должны четко отражать то, что они делают. `bindUseCase1` и т.п. не отражают сути, следует переименовать. Самое очевидное - `bindUseCase1` -> `bindRecipeDetailedInfoUseCase`

https://github.com/AmrAbuelhamd/Recipes2/blob/07ec466ea1d331378845cb8a602134450b4e1939/app/src/main/java/com/blogspot/soyamr/recipes2/domain/Repository.kt#L8
название репозитория должно отражать то, с чем в нем ведется работа. Очевидно, это репозиторий рецептов.

https://github.com/AmrAbuelhamd/Recipes2/blob/07ec466ea1d331378845cb8a602134450b4e1939/app/src/main/java/com/blogspot/soyamr/recipes2/data/RepositoryImpl.kt#L51
Нет необходимости явно проверять, есть ли интернет. Retrofit2 умеет обрабатывать такие случаи самостоятельно - он самостоятельно бросает соответствующие исключения.
Для централизованной обработки всех запросов можно использовать `Interceptor` - https://square.github.io/okhttp/interceptors/
В интерцепторе также можно добавлять к каждому запросу хэдер авторизации, если это требуется.

https://github.com/AmrAbuelhamd/Recipes2/blob/master/app/src/main/java/com/blogspot/soyamr/recipes2/domain/model/Result.kt
в стандартной поставке Котлина уже есть подобный класс - kotlin.Result, лучше использовать его. Также не стоит использовать частные классы ошибок в неудачном результате (в данном случае `class HttpError`), поскольку ошибки могут иметь совершенно разное происхождение - к примеру, неудачный запрос или проблема записи в БД. Прокидывать лучше максимально общий тип - `Throwable`.

https://github.com/AmrAbuelhamd/Recipes2/tree/master/app/src/main/java/com/blogspot/soyamr/recipes2/domain/interactors
не очень удачное название пакета, поскольку тут лежат юзкейсы, а не интеракторы.

Что бы можно было поправить, если совсем все сделано и нечем заняться:
1. на деталях рецепта при смене ориентации экрана теряется позиция скролла, то есть рецепт отображается сначала. Было бы неплохо позицию сохранять и восстанавливать.

**Comment by AmrAbuelhamd** [comment]
Исправил все замечания, спасибо большое.
