### ISSUE TITLE
Кодревью 2

### ISSUE THREAD

**Issue by AlexeiYakimov** [AmrAbuelhamd/Recipes2#2]
**Соответствие дизайну:**

1. Основной экран https://www.figma.com/file/uRmvw9ObwrRJu7dGsPXW12/Developer-Test?node-id=84%3A917
- в дизайне не показаны границы карточек, в приложении же они есть. Это нестрашно и не играет никакой роли, но
разница есть;
- в дизайне картинка рецепта в списке не имеет никакого отступа справа, в приложении же отступ есть. Это наталкивает на мысль, что элементы списка нужно делать "плоскими" и не в `MaterialCardView`;
- вертикальный отступ между карточками меньше, чем показано. По дизайну это 24dp, сейчас же где-то 16dp;
- меню с тремя точками: элементы в боттом шите написаны заглавными буквами, в дизайне не так https://www.figma.com/file/uRmvw9ObwrRJu7dGsPXW12/Developer-Test?node-id=117%3A84

2. Экран рецепта https://www.figma.com/file/uRmvw9ObwrRJu7dGsPXW12/Developer-Test?node-id=1035%3A873
- иконки шаринга и избранного сильно больше по размеру, чем в дизайне;
- блок с рекомендациями имеет высоту сильно больше, чем в дизайне https://www.figma.com/file/uRmvw9ObwrRJu7dGsPXW12/Developer-Test?node-id=1035%3A873
- расстояния между иконками поварского колпака сильно меньше, чем в дизайне https://www.figma.com/file/uRmvw9ObwrRJu7dGsPXW12/Developer-Test?node-id=1035%3A873 . Кроме того, сами иконки имеют плохое качество. Вероятно, нужно экспортировать SVG, а зачем импортировать векторную графику в ресурсы.

**Ревью кода:**

https://github.com/AmrAbuelhamd/Recipes2/blob/a9bab2260cf3f52e028818c80dfbe32ced12c9f0/app/src/main/java/com/blogspot/soyamr/recipes2/presentation/recipeslist/BottomSheetFragment.kt#L14
Название каждого элемента должно нести информацию о том, что этот элемент делает. В данном  случае это ботом шит, в котором содержатся элементы меню для сортировки. Название может быть, например, `SortRecipesBottomSheet`
То же самое можно сказать и про https://github.com/AmrAbuelhamd/Recipes2/blob/a9bab2260cf3f52e028818c80dfbe32ced12c9f0/app/src/main/java/com/blogspot/soyamr/recipes2/presentation/recipeitem/adapters/ViewPagerAdapter.kt#L9

Запись параметра сортировки
https://github.com/AmrAbuelhamd/Recipes2/blob/a9bab2260cf3f52e028818c80dfbe32ced12c9f0/app/src/main/java/com/blogspot/soyamr/recipes2/presentation/recipeslist/BottomSheetFragment.kt#L23
и его чтение во фрагменте
https://github.com/AmrAbuelhamd/Recipes2/blob/a9bab2260cf3f52e028818c80dfbe32ced12c9f0/app/src/main/java/com/blogspot/soyamr/recipes2/presentation/recipeslist/RecipesListFragment.kt#L37
крайне сложны для отладки и понимания. Код, конечно, полностью рабочий, но в таких случаях куда проще организовать все через метод `show` с использованием `SupportFragmentManager` родительского фрагмента. Слушать же события из диалога можно так https://developer.android.com/guide/fragments/communicate#pass-parent-child

https://github.com/AmrAbuelhamd/Recipes2/blob/a9bab2260cf3f52e028818c80dfbe32ced12c9f0/app/src/main/java/com/blogspot/soyamr/recipes2/presentation/image_viewer/ImageViewerFragment.kt#L82
Все, абсолютно все строки должны быть вынесены в ресурсы https://developer.android.com/guide/topics/resources/string-resource
Это связано с тем, что:
а) приложения очень часто локализуются;
б) одна и та же строка может потребоваться в разных местах кода.

https://github.com/AmrAbuelhamd/Recipes2/blob/a9bab2260cf3f52e028818c80dfbe32ced12c9f0/app/src/main/AndroidManifest.xml#L5
Не задекларировано использование `Manifest.permission.WRITE_EXTERNAL_STORAGE`. При скачивании картинки приложение почему-то не падает, хотя должно.

https://github.com/AmrAbuelhamd/Recipes2/blob/a9bab2260cf3f52e028818c80dfbe32ced12c9f0/app/src/main/java/com/blogspot/soyamr/recipes2/data/network/implementation/UtilsRepositoryImpl.kt#L12
Данный класс не относится к слою данных, это по сути своей просто утилита для определения, подключен ли сейчас интернет. Нам может потребоваться эта информация не только во врем запроса данных, но и в каких-то еще случаях. Ее следует разместить либо здесь https://github.com/AmrAbuelhamd/Recipes2/tree/master/app/src/main/java/com/blogspot/soyamr/recipes2/utils , либо в разделе менеджеров приложения.

https://github.com/AmrAbuelhamd/Recipes2/blob/a9bab2260cf3f52e028818c80dfbe32ced12c9f0/app/src/main/java/com/blogspot/soyamr/recipes2/data/common/contracts/LocaleContract.kt#L6
Опечатка, должно быть `LocalContract`

По клику на иконку сердечка и шаринга должно что-то происходить: можно показать, например, тост. По клику на иконку шаринга можно и вовсе показывать нативное меню: https://developer.android.com/training/sharing/send

**Comment by AmrAbuelhamd** [comment]
Solved issues
